WineOpener_proj/WineOpener/urls.py
# path()関数のインボート 
from django.urls import path
from WineOpener.views import live, readme, mypage, livebbs
# ルーティングの設定

app_name = 'WineOpener'

urlpatterns = [ 
    path('readme', readme.readme_view, name='readme'), 
    
    path('live', live.list_view, name='live_list'),
    path('live/live1', live.detail_view, name='live_detail'),
    path('live/live1/<slug:livewine_id>', live.wine_view, name='live_wine'),

    path('live/live1', livebbs.index, name='index'),
    path('live/live1/<pk>', livebbs.delete, name='delete'),

    path('mypage', mypage.mypage_top, name='mypage_top'),
    path('edit_cart/<slug:livewine_id>', live.edit_cart, name='edit_cart'), # 追加(2021/09/08)

    path('checkout/', mypage.checkout, name='checkout'),
    path('success/', mypage.success, name='success'),
    path('cancel/', mypage.cancel, name='cancel'),
    path('create_checkout_session/', mypage.create_checkout_session, name='checkout_session'), # 追加(2021/09/09)
]

WineOpener_proj/WineOpener_proj/urls.py
# path()関数、include()関数のインポート 
from django.urls import include, path
# 管理サイトの機能をインポート 
from django.contrib import admin 

from django.shortcuts import render
from django.contrib.auth.decorators import login_required


from WineOpener.views.register import register_view, done_view #追加(2021/09/06)

def index(request):
    contexts = {}
    return render(request,'index.html',contexts)


urlpatterns = [
    path('', index, name='index'),
    path('WineOpener/', include('WineOpener.urls')), # WineOpener アプリケーションの URL 設定を追加(2021/09/04) 
    path('admin/', admin.site.urls), # 管理サイト 
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register_view, name='register'),
    path('accounts/register/done', done_view, name='register_done'),
]

WineOpener_proj/WineOpener/models.py
from django.contrib.auth.models import User 
from django.db import models
 
GENDER_LIST = ( (0, '男性'), (1, '女性') )
dict_gender_list = dict(GENDER_LIST) #追加(2021/09/06)

#デフォルトであるdjango.dbのmodelsを継承して作成する
class Profile(models.Model):
    
    #django仕様のメタクラス(クラス自体の設定を記述)(管理画面での表示内容を設定)
    class Meta:
        verbose_name = 'ユーザー情報データ'
        verbose_name_plural = 'ユーザー情報データ'
    #ユーザーの設定。下記のフィールドとの紐づけはビューで行う
    user = models.OneToOneField(User, verbose_name='ユーザー',null=True, blank=True, on_delete=models.CASCADE)

    #フィールドの設定。コード１行がフィールド１列に対応する。
    id = models.CharField(max_length=6,primary_key=True) # 変更（2021/09/07）
    age = models.IntegerField('年齢')
    gender = models.IntegerField('性別',choices=GENDER_LIST)
    mobile = models.CharField('電話番号',max_length=12)
    email = models.CharField('メールアドレス',max_length=100)
    
    
    #管理画面で表示される文字列を定義する # 変更（2021/09/04）
    def __str__(self):
        user_str = ''
        if self.user is not None:
            user_str = '(' + self.user.username + ')'
        return self.id+' '\
            +str(self.age)+'歳 ' \
            +dict_gender_list.get(self.gender)+' ' \
            +str(self.mobile)+' ' \
            +str(self.email)+' '\
            +user_str

class Wine(models.Model): # 変更(2021/09/08)
    class Meta:
        verbose_name = '販売ワインデータ'
        verbose_name_plural = '販売ワインデータ'
    
    id = models.CharField('ワインID',max_length=6,primary_key=True) # 'A00001' # 変更（2021/09/07）
    thumbnail = models.CharField('サムネイル',max_length=50)      # 'WineOpener/images/live1.jpg'
    name = models.CharField('ワイン名',max_length=50)      # 'シャトー・オー・プニャン'
    price = models.IntegerField('価格')    # '2200'
    stock = models.IntegerField('在庫')    # '5'
    harvest_year = models.IntegerField('収穫年')       # '2018'
    producer = models.CharField('生産者',max_length=50)
    region = models.CharField('産地',max_length=50)
    style = models.CharField('タイプ',max_length=20)        # '赤ワイン', '白ワイン' など
    type = models.CharField('品種',max_length=50)

    owner = models.ForeignKey(Profile, # 変更予定(2021/09/08)
        verbose_name='所有者',
        null=True, blank=True,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.id+' '\
            +self.thumbnail+' ' \
            +self.name+' ' \
            +str(self.price)+' ' \
            +str(self.stock)+' ' \
            +str(self.harvest_year)+' '\
            +self.producer+' '\
            +self.region+' '\
            +self.style+' '\
            +self.type

class Cart(models.Model): #変更(2021/09/08)
    class Meta:
        verbose_name = 'カート情報'
        verbose_name_plural = 'カート情報'
    
    user_id = models.CharField('ユーザーID',max_length=6) # ユーザーID
    product_id = models.CharField('商品ID',max_length=6) # 商品ID
    timestamp = models.DateTimeField('追加日時',auto_now_add=True) # 追加日時

    def __str__(self):
        return self.user_id +' '\
            +self.product_id +' '\
            +self.timestamp

class Topic(models.Model):
    class Meta:
        managed = True
        verbose_name = 'コメント'
        verbose_name_plural = 'コメント'
        db_table = "topic"
    
    user_id = models.CharField('ユーザーID',max_length=6) # ユーザーID
    stream_id = models.CharField('コメントID',max_length=6) # コメントID
    comment = models.CharField('コメント', max_length=50) # コメント
    timestamp = models.DateTimeField('追加日時', auto_now_add=True) # 追加日時
    def __str__(self):
        return self.user_id + ' '\
            + self.stream_id + ' '\
            + self.comment + ' '\
            + str(self.timestamp)

WineOpener_proj/WineOpener/views/live.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import json
from WineOpener.models import Profile, Wine, Cart # 変更(2021/09/08)
from django.contrib.auth.models import User

import random

def list_view(request):
    return render(request, 'WineOpener/live_list.html')

@login_required
def detail_view(request):
    wine_informations = Wine.objects.all().order_by('id')
    return render(request, 'WineOpener/live_detail.html', {'wine_informations': wine_informations})

def wine_view(request, livewine_id):
    wine_information = get_object_or_404(Wine, id=livewine_id)
    return render(request, 'WineOpener/live_wine.html', {'wine_information': wine_information})

def edit_cart(request, livewine_id): 
    wine_information = get_object_or_404(Wine, id=livewine_id)
    user_id = request.user.id #ログインしているユーザーのIDを取得

    previous_cart = Cart.objects.filter(user_id=user_id, product_id=livewine_id) # 修正必要
    if previous_cart.exists(): # 編集前のカートの中身にこの商品はある？
        previous_cart.delete() # あればその商品を削除
    else:
        product = Cart(user_id=user_id, product_id=livewine_id) # なければユーザーID，商品ID，商品名，価格をカートに追加
        product.save()
    return render(request, 'WineOpener/live_wine.html', {'wine_information': wine_information})

WineOpener_proj/WineOpener/views/livebbs.py
from rest_framework import status, views, response
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import json
from WineOpener.models import Profile, Wine, Cart, Topic # 変更(2021/09/10)
from WineOpener.serializer import TopicSerializer
from django.contrib.auth.models import User

import random

from django.template.loader import render_to_string

class BbsView(views.APIView):
    def get(self,request,*args,**kwargs):

        data        = Topic.objects.all()
        context     = {"data":data}
        return render(request,"WineOpener/live_detail.html",context)

    def post(self, request, *args, **kwargs):

        serializer      = TopicSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        data        = Topic.objects.all()
        context     = {"data":data}
        content_data_string     = render_to_string('WineOpener/comment.html', context ,request)
        json_data               = { "content" : content_data_string }

        return JsonResponse(json_data)

index   = BbsView.as_view()

class BbsDeleteView(views.APIView):

    def delete(self, request, pk, *args, **kwargs):

        topic           = get_object_or_404(Topic,pk=pk)
        topic.delete()

        data        = Topic.objects.all()
        context     = {"data":data}
        content_data_string     = render_to_string('WineOpener/comment.html', context ,request)
        json_data               = { "content" : content_data_string }

        return JsonResponse(json_data)

delete  = BbsDeleteView.as_view()

WineOpener_proj/WineOpener/views/mypage.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import json
from WineOpener.models import Profile, Wine, Cart

# 以下4つ追加（決済用）(2021/09/09)
from django.conf import settings
import json
import stripe
from django.urls import reverse
from django.db.models import Sum

@login_required
def mypage_top(request):
    user = request.user
    profile = user.profile
    user_id = user.id # 追加(2021/09/08)
    products = Cart.objects.filter(user_id=user_id) # ユーザーIDがログイン中しているユーザのIDになっているproductsを取り出す 追加(2021/09/08)
    return render(request, 'WineOpener/mypage.html', {'profile':profile,'products':products}) #'assessments':myassessments

def success(request): # 決済成功時の関数　追加(2021/09/09)
    return render(request, 'WineOpener/success.html') # テンプレートを表示するだけ


def cancel(request): # 決済中止時の関数
    return render(request, 'WineOpener/cancel.html') # テンプレートを表示するだけ


def checkout(request): # 決済内容確認時の関数
    key_data = {
        "publishable_key":settings.STRIPE_PUBLISHABLE_KEY, # settings.pyから読み込んだ公開鍵をjson形式にしてテンプレートcheckout.htmlに渡す
    }

    user = request.user
    user_id = user.id
    user_name = user.username
    product_id = Cart.objects.filter(user_id=user_id).values_list('product_id', flat=True) # ユーザーIDがログインしているユーザのIDになっている"products"を取り出す 追加(2021/09/09)
    products = Wine.objects.filter(id__in=product_id).values('id', 'name', 'price')
    price_total = Wine.objects.filter(id__in=product_id).aggregate(Sum('price'))['price__sum']
    price_total = round(price_total)

    return render(request, 'WineOpener/checkout.html', {'data_json':json.dumps(key_data), "products":products, "price":price_total, "user_id":user_name}) # 追加(2021/09/09)「"user_id":user_name」の箇所合ってる？？

def create_checkout_session(request):# 「この商品を購入」ボタンが押された時の関数 
    stripe.api_key = settings.STRIPE_SECRET_KEY # settings.pyから秘密鍵を読み込む

    user = request.user
    user_id = user.id
    user_name = user.username
    product_id = Cart.objects.filter(user_id=user_id).values_list('product_id', flat=True) # ユーザーIDがログインしているユーザのIDになっている"products"を取り出す 追加(2021/09/09)
    products = Wine.objects.filter(id__in=product_id).values('id', 'name', 'price')
    price_total = Wine.objects.filter(id__in=product_id).aggregate(Sum('price'))['price__sum']
    price_total = round(price_total)

    try:
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'], # カード決済
            line_items=[ # 決済内容を記述
                {
                    'price_data': {
                        'currency': 'jpy', # 通貨（円）
                        'unit_amount': 2000, # 金額
                        'product_data': { # 商品説明・画像
                            'name': 'sample house',
                            'images': ['http://gahag.net/img/201606/12s/gahag-0095672681-1.jpg'],
                            },
                    },
                    'quantity': 1, # 個数
                },
            ],
            mode='payment',
            success_url=request.build_absolute_uri(reverse('WineOpener:success')), # 成功すれば"success"へ
            cancel_url=request.build_absolute_uri(reverse('WineOpener:cancel')), # 中止すれば"cancel"へ
        )

        print(checkout_session.id)
        return JsonResponse({'id': checkout_session.id})
    except Exception as e:
        return JsonResponse({'error':str(e)})

WineOpener_proj/WineOpener/views/readme.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
#from django.contrib.auth.decorators import login_required

#import json
#from streetfood.models import Food, Profile, Cart # 変更予定(2021/09/07)


def readme_view(request):
    return render(request, 'WineOpener/readme.html')

WineOpener_proj/WineOpener/views/register.py
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from WineOpener.register_form import RegisterForm

class RegisterView(CreateView):
    template_name = 'registration/register_form.html'
    form_class = RegisterForm
    success_url = reverse_lazy('register_done')

register_view = RegisterView.as_view()

class DoneView(TemplateView):
    template_name = 'registration/register_done.html'

done_view = DoneView.as_view()

WineOpener_proj/WineOpener/templates/WineOpener/cancel.html
{% extends "base.html" %}


{% block title %}購入キャンセル{% endblock title %}

{% block content %}
<hr><hr><hr>
 <section>
   <h1>購入がキャンセルされました</h1>
   <a href="{% url 'index' %}">トップページにもどる</a>
 </section>
 <hr><hr><hr>
{% endblock content %}

WineOpener_proj/WineOpener/templates/WineOpener/comment.html
{% for content in data %}
<div id="{{ content.id }}" class="border" onclick="delete_comment('{{ content.id }}')">
    {{ content.comment }}
</div>
{% endfor %}

WineOpener_proj/WineOpener/templates/WineOpener/live_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>WineOpener</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" href="{% static 'WineOpener/css/style.css' %}"> <!--変更-->
<script src="{% static 'WineOpener/js/openclose.js' %}"></script> <!--変更-->
<script src="{% static 'WineOpener/js/fixmenu_pagetop.js' %}"></script> <!--変更-->
<script src="{% static 'WineOpener/js/vivus.js' %}"></script> <!--変更-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> <!--変更-->
<script src="{% static 'WineOpener/js/ajax.js' %}"></script> <!--追加(2021/09/10)-->
<script src="{% static 'WineOpener/js/onload.js' %}"></script> <!--追加(2021/09/10)-->
</head>

<body>
<div id="container">

<header>
<h1 id="logo"><a href="/"><img src="{% static 'WineOpener/images/logo_wineopener.jpg' %}" alt="WineOpener"></a></h1>
<!--PC用（901px以上端末）メニュー-->
<nav id="menubar">
<ul>
<li><a href="/WineOpener/readme">READ ME</a></li>
<li class="current"><a href="/WineOpener/live">Live配信一覧</a></li>
<li><a href="profile.html">PROFILE</a></li>
<li><a href="event.html">EVENT</a></li>
<li><a href="discography.html">DISCOGRAPHY</a></li>
<li><a href="contact.html">CONTACT</a></li>
</ul>
</nav>
<ul class="icon">
    {% if user.is_authenticated %}
	<li><a href="/WineOpener/mypage">マイページ</a></li>
    <li><a href="/accounts/logout">ログアウト</a></li>
	{% else %}
    <li><a href="/accounts/register">会員登録</a></li>
    <li><a href="/accounts/login">ログイン</a></li>
	{% endif %}
</ul>
</header>

<div id="contents">

<div id="main">

<section>
<h2>Live<span>Live配信1</span></h2>
<h3>【ワイン】スターワインの仕掛け人が選ぶヴィンテージワインコレクション</h3>
<dl class="news">
    <iframe src="https://twitcasting.tv/g:105881481929015164763/embeddedplayer/live?auto_play=false&default_mute=true" width="640px" height="605px" frameborder="0" allowfullscreen></iframe>
    <table class="ta1">
        <caption>販売中商品</caption>
        <tr>
            <th>Image</th> <th>Detail</th> <th>Stock</th> <th></th>
        </tr>
        
        {% for wine_information in wine_informations %}
        <tr>
            <th><img src="{% static '{{ wine_information.thumbnail }}' %}" width="100px" height="100px"  alt="wine_thumbnail"></th><!--画像の挿入が未実装…-->
            <th>{{ wine_information.name }}<br>・価格：￥{{ wine_information.price }}<br>・収穫年：{{ wine_information.harvest_year }}年<br>・生産者：{{ wine_information.producer }}<br>・産地：{{ wine_information.region }}<br>・タイプ：{{ wine_information.style }}<br>・品種：{{ wine_information.type }}</th>
            <th>{{ wine_information.stock }}</th>
            <th>
                <a href="{% url 'WineOpener:live_wine' livewine_id=wine_information.id %}">
                    購入ページ
                </a>
            </th>
        </tr>
        {% endfor %}
        
    </table>
    <div class="clear">
        <aside class="fl w25"><img src="{% static 'WineOpener/images/photo1.png' %}" alt=""></aside>
        
        <section class="fr w70">
        <h2>PROFILE<span>カスタニエ・クリストフ (Christophe CASTAGNE)</span></h2>
        <p>ラティテュード株式会社 (Latitude K.K)　代表取締役</p>
        <h3>社長挨拶　Latitude の願い</h3>
        <p>私、Christophe CASTAGNE（カスタニエ・クリストフ）は1970年にフランスで生まれました。<br>「新しい人生経験」を求め、幼少時代に母国フランスを発ち、<br>その後の18年間をアフリカで、<br>4年間をアメリカ、<br>8年間を日本、そして今私自身のブランドを立ち上げようと決心しました。</p>
        <p>1980年代後半からワインビジネスを確立するために来日するようになり、<br>それから約14年間の歳月の中でワインのフリーランス、スペシャリストとして経験を積み、<br>「日本の皆様」と「ワイン」の橋渡しに貢献できるよう取り組んで参りました。<br>時にはワインセミナーを開催したり、日本及び各国のワイン展示会への出店、<br>また店頭でのデモンストレーションも数多く経験させていただきました。<br>そのような体当たりの経験ができたからころ、日本のワイン市場を体で感じることができるようになったのだと思います。</p>
        </section>        
    </div>        
</dl>

</section>

</div>
<!--/#main-->

<div id="sub">

<h2>ARCHIVE</h2>
<ul class="submenu">
<li><a href="#">2021年</a></li>
<li><a href="#">2020年</a></li>
<li><a href="#">2019年</a></li>
<li><a href="#">2018年</a></li>
<li><a href="#">2017年</a></li>
<!--追加(2021/09/10)-->
<form>
    {% csrf_token %}
    <textarea id="comment" class="form-control" name="comment"></textarea>
    <input id="submit" type="button" value="送信">
</form>
<div id="comment_area">
    {% include 'WineOpener/comment.html' %}
</div>
</ul>

</div>
<!--/#sub-->

</div>
<!--/#contents-->

<footer>
<small>Copyright&copy; <a href="/">INDIES BAND</a> All Rights Reserved.</small>
<span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
</footer>

</div>
<!--/#container-->

<!--小さな端末用（900px以下端末）メニュー-->
<nav id="menubar-s">
<ul>
<li><a href="readme.html">READ ME</a></li>
<li><a href="live_list.html">NEWS</a></li>
<li><a href="profile.html">PROFILE</a></li>
<li><a href="event.html">EVENT</a></li>
<li><a href="discography.html">DISCOGRAPHY</a></li>
<li><a href="contact.html">CONTACT</a></li>
</ul>
</nav>

<!--ページの上部に戻る「↑」ボタン-->
<p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>

<!--メニュー開閉ボタン-->
<div id="menubar_hdr" class="close"></div>

<!--メニューの開閉処理条件設定　900px以下-->
<script>
if (OCwindowWidth() <= 900) {
	open_close("menubar_hdr", "menubar-s");
}
</script>

<!--パララックス用ファイル読み込み
<script src="{% static 'WineOpener/js/jquery.inview.js' %}"></script>
<script src="{% static 'WineOpener/js/jquery.inview_set.js' %}"></script>-->

</body>
</html>

WineOpener_proj/WineOpener/templates/WineOpener/live_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>WineOpener</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" href="{% static 'WineOpener/css/style.css' %}"> <!--変更-->
<script src="{% static 'WineOpener/js/openclose.js' %}"></script> <!--変更-->
<script src="{% static 'WineOpener/js/fixmenu_pagetop.js' %}"></script> <!--変更-->
<script src="{% static 'WineOpener/js/vivus.js' %}"></script> <!--変更-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> <!--変更-->
</head>

<body>
<div id="container">

<header>
<h1 id="logo"><a href="/"><img src="{% static 'WineOpener/images/logo_wineopener.jpg' %}" alt="WineOpener"></a></h1>
<!--PC用（901px以上端末）メニュー-->
<nav id="menubar">
<ul>
<li><a href="/WineOpener/readme">READ ME</a></li>
<li class="current"><a href="/WineOpener/live">Live配信一覧</a></li>
<li><a href="profile.html">PROFILE</a></li>
<li><a href="event.html">EVENT</a></li>
<li><a href="discography.html">DISCOGRAPHY</a></li>
<li><a href="contact.html">CONTACT</a></li>
</ul>
</nav>
<ul class="icon">
    {% if user.is_authenticated %}
	<li><a href="/WineOpener/mypage">マイページ</a></li>
    <li><a href="/accounts/logout">ログアウト</a></li>
	{% else %}
    <li><a href="/accounts/register">会員登録</a></li>
    <li><a href="/accounts/login">ログイン</a></li>
	{% endif %}
</ul>
</header>

<div id="contents">

<div id="main">

<section>

<h2>Live配信一覧<span>最新情報のご案内</span></h2>

<dl class="news">

<dt>2021/09/06<span class="icon event">NEW</span></dt> <!--変更(2021/09/06)-->
<dd>【ワイン】スターワインの仕掛け人が選ぶヴィンテージワインコレクション<br><a href="{% url 'WineOpener:live_detail' %}">配信はこちら</a></dd>

<dt>20XX/00/00<span class="icon">EVENT</span></dt>
<dd><img src="images/sample1_mini.jpg" alt="" class="img">「INFORMATIOM」「EVENT」「MEDIA」のアイコンの文字は直接html側で入れ替え可能です。<br>
色はcssフォルダのstyle.cssの、<br>
<span class="color1">/*NEWSブロック内のアイコン</span><br>
で調整可能。</dd>

<dt>20XX/00/00<span class="icon media">MEDIA</span></dt>
<dd><img src="images/sample1_mini.jpg" alt="" class="img">imgタグに<span class="color1">class=&quot;img&quot;</span>をつけると右側の画像のように小さな画像になって右に回り込みとなります。画像幅はcssフォルダのstyle.cssで調整可能。</dd>

<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>

<dt>20XX/00/00</dt>
<dd>画像にclass指定がなければこのようにブロック幅一杯に表示されます。<img src="images/1.jpg" alt=""></dd>

</dl>

</section>

</div>
<!--/#main-->

<div id="sub">

<h2>ARCHIVE</h2>
<ul class="submenu">
<li><a href="#">2021年</a></li>
<li><a href="#">2020年</a></li>
<li><a href="#">2019年</a></li>
<li><a href="#">2018年</a></li>
<li><a href="#">2017年</a></li>
</ul>

</div>
<!--/#sub-->

</div>
<!--/#contents-->

<footer>
<small>Copyright&copy; <a href="/">INDIES BAND</a> All Rights Reserved.</small>
<span class="pr"><a href="https://template-party.com/" target="_blank">《Web Design:Template-Party》</a></span>
</footer>

</div>
<!--/#container-->

<!--小さな端末用（900px以下端末）メニュー-->
<nav id="menubar-s">
<ul>
<li><a href="readme.html">READ ME</a></li>
<li><a href="live_list.html">NEWS</a></li>
<li><a href="profile.html">PROFILE</a></li>
<li><a href="event.html">EVENT</a></li>
<li><a href="discography.html">DISCOGRAPHY</a></li>
<li><a href="contact.html">CONTACT</a></li>
</ul>
</nav>

<!--ページの上部に戻る「↑」ボタン-->
<p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>

<!--メニュー開閉ボタン-->
<div id="menubar_hdr" class="close"></div>

<!--メニューの開閉処理条件設定　900px以下-->
<script>
if (OCwindowWidth() <= 900) {
	open_close("menubar_hdr", "menubar-s");
}
</script>

<!--パララックス用ファイル読み込み-->
<script src="{% static 'WineOpener/js/jquery.inview.js' %}"></script>
<script src="{% static 'WineOpener/js/jquery.inview_set.js' %}"></script>

</body>
</html>

WineOpener_proj/WineOpener/templates/WineOpener/mypage.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}Mypage{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">Mypage</h4>

    <h5>基本情報</h5>
    <p><b>{{ user.username }}</b> さん</p>
    <p>年齢: {{ user.profile.age }}歳</p>
    <p>性別: {{ user.profile.get_gender_display }}</p>
    <p>電話番号: {{ user.profile.mobile }}</p>
    <p>メールアドレス: {{ user.profile.email }}</p>
    <p></p>
    <p>ユーザー名またはパスワードの編集は <a href="/accounts">こちら</a>(未実装)</p>

    <h5>カート</h5>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col">商品ID</th>
                <th scope="col">時刻</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <th scope="row">
                    {{ product.product_id }}
                </th>
                <th scope="row">
                    {{ product.timestamp }}
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form action="{% url 'WineOpener:checkout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Buy All" class="btn btn-primary mt-2">
    </form>
{% endblock %}

WineOpener_proj/WineOpener/templates/WineOpener/success.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}決済成功{% endblock title %}

{% block content %}
 <section>
   <hr><hr><hr>
   <h1>購入ありがとうございます！</h1>
   <a href="{% url 'index' %}">トップページにもどる</a>
 </section>
 {% endblock content %}