streetfood_proj/streetfood/urls.py
# path()関数のインボート 
from django.urls import path
from . import views
from streetfood.views import concept, food, topic, mypage # 追加(2021.08.29.13:34)


# ルーティングの設定 

app_name = 'streetfood'
#変更！
urlpatterns = [
    path('concept',concept.concept_top, name='concept_top'),

    path('food', food.list_view, name='food_list'),
    path('food/<slug:food_id>', food.detail_view, name='food_detail'),

    path('topic', topic.live_view, name='topic_live'),# 追加(2021.08.29.20:29)

    path('mypage', mypage.mypage_top, name='mypage_top'),# 追加(2021.08.29.16:03)
    path('edit_cart/<slug:food_id>', food.edit_cart, name='edit_cart'), #追加(2021.08.29.16:53)
    ]

streetfood_proj/streetfood_proj/urls.py
# path()関数、include()関数のインポート 
from django.urls import include, path
from . import settings # 追加(2021.08.29.18:07)
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# 管理サイトの機能をインポート 
from django.contrib import admin 

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from streetfood.views.register import register_view, done_view #追加！

def index(request):
    contexts = {}
    return render(request,'index.html',contexts)


urlpatterns = [
    path('', index, name='index'), #追加！
    # streetfood アプリケーションの URL 設定を追加 
    path('streetfood/', include('streetfood.urls')), 
    # 管理サイト 
    path('admin/', admin.site.urls), 
    #追加ここから
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register_view, name='register'),
    path('accounts/register/done', done_view, name='register_done'),
    #追加ここまで
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

streetfood_proj/streetfood/models.py
from django.contrib.auth.models import User # 追加(2021.08.29.0:23)
from django.db import models 
 
GENDER_LIST = ( (0, '男性'), (1, '女性') )
dict_gender_list = dict(GENDER_LIST)

#デフォルトであるdjango.dbのmodelsを継承して作成する
class Profile(models.Model):
    
    #django仕様のメタクラス(クラス自体の設定を記述)(管理画面での表示内容を設定)
    class Meta:
        verbose_name = 'ユーザー情報データ'
        verbose_name_plural = 'ユーザー情報データ'
    #ユーザーの設定。下記のフィールドとの紐づけはビューで行う
    user = models.OneToOneField(User, verbose_name='ユーザー',null=True, blank=True, on_delete=models.CASCADE)

    #フィールドの設定。コード１行がフィールド１列に対応する。
    id = models.CharField(max_length=6,primary_key=True)
    age = models.IntegerField('年齢')
    gender = models.IntegerField('性別',choices=GENDER_LIST)
    pref_name = models.CharField('都道府県',max_length=20)      # '東京都'
    city_name = models.CharField('市区町村',max_length=50)      # '世田谷区'
    district_name = models.CharField('町丁目',max_length=50)    # '喜多見７丁目'
    
    #管理画面で表示される文字列を定義する
    def __str__(self):
#加筆ここから
        user_str = ''
        if self.user is not None:
            user_str = '(' + self.user.username + ')'
#加筆ここまで
        return self.id+' '+str(self.age)+'歳 ' \
            +dict_gender_list.get(self.gender)+' ' \
                +self.pref_name+self.city_name+self.district_name

class Food(models.Model):
    class Meta:
        verbose_name = '商品データ'
        verbose_name_plural = '商品データ'
    
    id = models.CharField('商品ID',max_length=6,primary_key=True) # 'A00001'
    food_name = models.CharField('商品名',max_length=20)
    price = models.FloatField('価格')
    image = models.CharField('画像ファイル',max_length=20)

#加筆ここから
    owner = models.ForeignKey(Profile,
        verbose_name='所有者',
        null=True, blank=True,
        on_delete=models.CASCADE
    )

#加筆ここまで

    def __str__(self):
        return self.id+' '+self.food_name

class Cart(models.Model):
    
    #django仕様のメタクラス(クラス自体の設定を記述)(管理画面での表示内容を設定)
    class Meta:
        verbose_name = 'カート情報'
        verbose_name_plural = 'カート情報'
    #ユーザーID
    user_id = models.CharField(max_length=6)
    #商品ID
    product_id = models.CharField(max_length=6)
    #追加時刻
    timestamp = models.DateTimeField('追加日時', auto_now_add=True)
    # ユーザー住所
    pref_name = models.CharField('都道府県',max_length=20)      # '東京都'
    city_name = models.CharField('市区町村',max_length=50)      # '世田谷区'
    district_name = models.CharField('町丁目',max_length=50)    # '喜多見７丁目'
    #管理画面で表示される文字列を定義する
    def __str__(self):
        return self.user_id + ' ' + self.product_id

streetfood_proj/streetfood/views/concept.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import json
from streetfood.models import Food, Profile, Cart


def concept_top(request):
    return render(request, 'streetfood/concept.html') #'assessments':myassessments

streetfood_proj/streetfood/views/food.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages

from django.contrib.auth.decorators import login_required #追加(2021.08.29.14:01)

from streetfood.models import Profile, Food, Cart
from django.contrib.auth.models import User #User追加
from django.core.paginator import Paginator
from streetfood.models import Food

import random

def list_view(request):
    food_list = Food.objects.all().order_by('-id')
    paginator = Paginator(food_list, 20) # ページ当たり20個表示

    try:
        page = int(request.GET.get('page'))
    except:
        page = 1

    foods = paginator.get_page(page)
    return render(request, 'streetfood/food_list.html', {'foods': foods, 'page': page, 'last_page': paginator.num_pages})

def detail_view(request, food_id):
    food = get_object_or_404(Food, id=food_id)

    try:
        page = int(request.GET.get('from_page'))
    except:
        page = 1
    return render(request, 'streetfood/food_detail.html', {'food': food, 'page': page })

def edit_cart(request, food_id):
    #表示しているページの物件を取得
    food = get_object_or_404(Food, id=food_id)
    #遷移前の一覧ページを取得
    try:
        page = int(request.GET.get('from_page'))
    except:
        page = 1
    #ログインしているユーザのIDを取得
    user_id = request.user.id
    #編集前のカートの中身にこの商品はある？
    previous_cart = Cart.objects.filter(user_id=user_id, product_id=food_id)
    if previous_cart.exists():
        #あればその商品を削除
        previous_cart.delete()
    else:
        #無ければユーザID・商品IDの組をカートに追加
        #productはCartクラスのインスタンス
        product = Cart(user_id=user_id, product_id=food_id)
        product.save()
    return render(request, 'streetfood/food_detail.html', {'food': food, 'page': page })

streetfood_proj/streetfood/views/mypage.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

import json
from streetfood.models import Food


@login_required
def mypage_top(request):
    user = request.user
    profile = user.profile
    # owner_id=profile.idの商品を取り出し、テンプレートに渡す。
    myfoods = Food.objects.filter(owner_id=profile.id)

    return render(request, 'streetfood/mypage.html', {'profile':profile,'foods':myfoods}) #'assessments':myassessments

streetfood_proj/streetfood/views/register.py
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from streetfood.register_form import RegisterForm

class RegisterView(CreateView):
    template_name = 'registration/register_form.html'
    form_class = RegisterForm
    success_url = reverse_lazy('register_done')

register_view = RegisterView.as_view()

class DoneView(TemplateView):
    template_name = 'registration/register_done.html'

done_view = DoneView.as_view()

streetfood_proj/streetfood/views/topic.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages


from django.core.paginator import Paginator
from streetfood.models import Food

import random

def live_view(request):
    foods = Food.objects.all().order_by('-id')
    return render(request, 'streetfood/topic_live.html', {'foods': foods})

streetfood_proj/streetfood/templates/base.html
{% load i18n %}
{% load static from staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <title>STREETFOOD</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'streetfoood/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
        integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
        crossorigin="" />

    <link rel="stylesheet" href="{% static 'streetfood/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'streetfood/css/homepage.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
        integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
        crossorigin=""></script>

    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-tilelayer-geojson/1.0.4/TileLayer.GeoJSON.min.js"></script>

</head>



<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">STREETFOOD</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/streetfood/food">商品一覧</a>
                            <a class="dropdown-item" href="/streetfood/recommend">おすすめ商品</a>
                            <!-- <div class="dropdown-divider"></div> -->
                            <a class="dropdown-item" href="/streetfood/assess">商品を売る(査定)</a>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/streetfood/mypage">マイページ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/logout">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/register">会員登録</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login">ログイン</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {{ content }}
        {% endblock %}
        {% block extra_js %}{% endblock %}

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; techpreneur 2019</p>
        </div>
        <!-- /.container -->
    </footer>

    <script type="text/javascript" src="{% static 'steetfood/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'streetfood/js/index.js' %}"></script>
    <script type="text/javascript" src="{% static 'streetfood/js/gulpfile.js' %}"></script>

</body>

</html>

streetfood_proj/streetfood/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}屋台が自宅に！{% endblock title %}
{% block content %}
{% load static %}

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 style="margin-top: 5.0rem;">STREETFOOD</h1>
            <h2>
                <center>おうちで<br>お祭り気分</center>
            </h2>
            <div class="list-group">
                <a href="/streetfood/concept" class="list-group-item">STREETFOODとは</a>
                <a href="/streetfood/topic" class="list-group-item">Live配信中</a> 
                <a href="/streetfood/food" class="list-group-item">商品一覧</a>
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9" style="margin-top: 4.0rem;">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                </ol>
                <div class="carousel-inner" role="listbox">

                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="/media/img/spring.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/media/img/summer.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/media/img/autumn.jpg" alt="Third slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="/media/img/winter.jpg" alt="Fourth slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <h4>
                <center>おすすめ商品</center>
            </h4>
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top"
                                src="/media/img/image4.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="./streetfood/food/A00004">たこ焼き</a>
                            </h4>
                            <h5>価格：500円</h5>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top"
                                src="/media/img/image6.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="./streetfood/food/A00006">焼きそば</a>
                            </h4>
                            <h5>価格：500円</h5>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top"
                                src="/media/img/image12.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="./streetfood/food/A00012">ラムネ</a>
                            </h4>
                            <h5>価格：300円</h5>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>
            </div>

            <h4>
                <center>その他のシーズン商品</center>
            </h4>
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top"
                                src="/media/img/image8.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="./streetfood/food/A00008">焼きとうもろこし</a>
                            </h4>
                            <h5>価格：500円</h5>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top"
                                src="/media/img/image5.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="./streetfood/food/A00005">チョコバナナ</a>
                            </h4>
                            <h5>価格：300円</h5>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#"><img class="card-img-top"
                                src="/media/img/image13.jpg" alt=""></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="./streetfood/food/A00013">生ビール</a>
                            </h4>
                            <h5>価格：300円</h5>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->


{% endblock content %}

streetfood_proj/streetfood/templates/streetfood/concept.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}STREETFOODとは{% endblock title %}
{% block content %}
{% load static %}



<!-- Page Content -->

<section style="margin-top: 10.0rem;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="/media/img/spring.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">STREETFOODとは</h2>
          <p>イベント時限定の屋台グルメ配達サイト</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="/media/img/summer.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-3">
          <h2 class="display-4">四季折々のイベントをLive配信</h2>
          <p>Live配信とともに屋台グルメをおうちで楽しむ</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="/media/img/autumn.jpg" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-3">
          <h2 class="display-4">配達までの時間を　リアルタイムで表示</h2>
          <p>※今回実装には至りませんでした</p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

streetfood_proj/streetfood/templates/streetfood/food_detail.html
{% extends "base.html" %}
{% load mathfilters %}
{% load staticfiles %}

{% block title %}物件の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">商品の詳細</h4>

<table class="table table-striped table-bordered">
    <tbody>
        <tr>
            <th scope="row">商品ID</th>
            <td>{{ food.id }}</td>
        </tr>
        <tr>
            <th scope="row">商品名</th>
            <td>{{ food.food_name }}</td>
        </tr>
        <tr>
            <th scope="row">価格</th>
            <td>{{ food.price }}</td>
        </tr>
    </tbody>
</table>

<form action="{% url 'streetfood:edit_cart' food_id=food.id %}?from_page={{page}}" method="post">
    {% csrf_token %}
    <input type="submit" value="add/delete" class="btn btn-primary mt-2">
</form>

<a href="{% url 'streetfood:food_list' %}?page={{ page }}">一覧へ戻る</a>
{% endblock %}

streetfood_proj/streetfood/templates/streetfood/food_list.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}商品の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">商品の一覧</h4>


<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">商品ID</th>
            <th scope="col">商品名</th>
            <th scope="col">価格</th>
            <th scope="col">写真</th>
        </tr>
    </thead>
    <tbody>
        {% for food in foods %}
        <tr>
            <th scope="row">
                <a href="{% url 'streetfood:food_detail' food_id=food.id %}">
                    {{ food.id }}
                </a>
            </th>
            <td>{{ food.food_name }}</td>
            <td>{{ food.price }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if page > 1 %}
<a href="{% url 'streetfood:food_list' %}?page={{ page|sub:1 }}">前のページ</a>
{% endif %}
{% if page < last_page %}
<a href="{% url 'streetfood:food_list' %}?page={{ page|add:1 }}">次のページ</a>
{% endif %}
{% endblock %}

streetfood_proj/streetfood/templates/streetfood/mypage.html
{% extends "base.html" %}
{% load mathfilters %}

{% block title %}マイページ{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">マイページ</h4>

    <h5>基本情報</h5>
    <p><b>{{ user.username }}</b> さん</p>
    <p>年齢: {{ user.profile.age }}歳</p>
    <p>性別: {{ user.profile.get_gender_display }}</p>
    <p>都道府県: {{ user.profile.pref_name }}</p>
    <p>市区: {{ user.profile.city_name }}</p>
    <p>町村: {{ user.profile.district_name }}</p>
    <p></p>
    <p>ユーザー名またはパスワードの編集は <a href="/accounts">こちら</a>(未実装)</p>

    <h5>カート</h5>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
            <th scope="col">商品ID</th>
            <th scope="col">時刻</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
            <th scope="row">
                {{ product.product_id }}
            </th>
            <th scope="row">
                {{ product.timestamp }}
            </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}